# Generated by Django 3.0.3 on 2020-02-04 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_number', models.IntegerField(max_length=8)),
                ('brand', models.CharField(choices=[('P', 'Pop!'), ('A', 'Action Figures'), ('D', 'Dorbz'), ('H', 'Hikari')], default='P', max_length=1)),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pop')),
            ],
        ),
    ]
