# Generated by Django 3.0.3 on 2020-02-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='item_number',
            field=models.IntegerField(),
        ),
    ]
