# Generated by Django 3.0.3 on 2020-02-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200205_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='accessorys',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
